import { z } from 'zod';
export const catalogSourceSchema=z.enum(['manual','instagram_public','demo_generated','csv','json','erp']);
export const availabilitySchema=z.enum(['available','out_of_stock','preorder']);
export const productStatusSchema=z.enum(['draft','published','archived']);
export const canonicalVariantSchema=z.object({externalId:z.string().trim().min(1).optional(),sku:z.string().trim().min(1).optional(),size:z.string().trim().min(1).optional(),color:z.string().trim().min(1).optional(),priceOverrideCents:z.number().int().nonnegative().optional(),availability:availabilitySchema,stockQty:z.number().int().nonnegative().nullable().optional(),active:z.boolean()});
export const canonicalProductSchema=z.object({externalId:z.string().trim().min(1).optional(),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),title:z.string().trim().min(1),subtitle:z.string().trim().optional(),description:z.string(),categorySlug:z.string().trim().optional(),priceCents:z.number().int().nonnegative(),compareAtPriceCents:z.number().int().nonnegative().optional(),currency:z.literal('ARS'),status:productStatusSchema,featured:z.boolean(),variants:z.array(canonicalVariantSchema).min(1),source:catalogSourceSchema,sourceName:z.string().trim().optional(),demoData:z.boolean()}).superRefine((v,ctx)=>{if(v.compareAtPriceCents!==undefined&&v.compareAtPriceCents<v.priceCents)ctx.addIssue({code:'custom',path:['compareAtPriceCents'],message:'compare_at_must_be_gte_price'});});
export type CatalogSource=z.infer<typeof catalogSourceSchema>; export type CanonicalVariantInput=z.infer<typeof canonicalVariantSchema>; export type CanonicalProductInput=z.infer<typeof canonicalProductSchema>;
export type PublicVariant={id:string;sku:string|null;size:string|null;color:string|null;priceOverrideCents:number|null;availability:z.infer<typeof availabilitySchema>;stockQty:number|null;active:boolean};
export type PublicMedia={id:string;altText:string;originalKey:string;smallKey:string|null;largeKey:string|null;width:number|null;height:number|null};
export type PublicCategory={id:string;slug:string;name:string;description:string|null;sortOrder:number};
export type PublicProduct={id:string;slug:string;title:string;subtitle:string|null;description:string;priceCents:number;compareAtPriceCents:number|null;currency:'ARS';featured:boolean;category:PublicCategory|null;media:PublicMedia[];variants:PublicVariant[]};
export interface CatalogSourceAdapter<T>{parse(input:T):Promise<CanonicalProductInput[]>}
function csvMatrix(text:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){field+='"';i++;continue;}if(ch==='"'){quoted=!quoted;continue;}if(ch===','&&!quoted){row.push(field);field='';continue;}if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(field);if(row.some(Boolean))rows.push(row);row=[];field='';continue;}field+=ch;}row.push(field);if(row.some(Boolean))rows.push(row);return rows;}
const bool=(v:string)=>/^(true|1|yes)$/i.test(v.trim());
export async function parseCsvCatalog(text:string){const m=csvMatrix(text.replace(/^\uFEFF/,''));if(m.length<2)return[];const h=m[0].map(v=>v.trim());return m.slice(1).map((cells,index)=>{const r=Object.fromEntries(h.map((k,i)=>[k,cells[i]??'']));let variants:unknown;try{variants=JSON.parse(r.variants||'[]');}catch{throw new Error(`csv_invalid_variants_row_${index+2}`);}return canonicalProductSchema.parse({externalId:r.externalId||undefined,slug:r.slug,title:r.title,subtitle:r.subtitle||undefined,description:r.description||'',categorySlug:r.categorySlug||undefined,priceCents:Number(r.priceCents),compareAtPriceCents:r.compareAtPriceCents?Number(r.compareAtPriceCents):undefined,currency:'ARS',status:r.status||'draft',featured:bool(r.featured||'false'),variants,source:r.source||'csv',sourceName:r.sourceName||undefined,demoData:bool(r.demoData||'false')});});}
function stable(value:unknown):string{if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;if(value&&typeof value==='object'){const o=value as Record<string,unknown>;return`{${Object.keys(o).sort().map(k=>`${JSON.stringify(k)}:${stable(o[k])}`).join(',')}}`;}return JSON.stringify(value);}
function sha256Ascii(input:string){const rotr=(v:number,a:number)=>(v>>>a)|(v<<(32-a)),M=2**32,w:number[]=[],hash:number[]=[],k:number[]=[],comp:Record<number,boolean>={};const bit=input.length*8;let pc=0;for(let n=2;pc<64;n++){if(!comp[n]){for(let i=n*n;i<313;i+=n)comp[i]=true;hash[pc]=(Math.sqrt(n)*M)|0;k[pc]=((n**(1/3))*M)|0;pc++;}}input+='\x80';while(input.length%64!==56)input+='\x00';for(let i=0;i<input.length;i++)w[i>>2]|=input.charCodeAt(i)<<((3-i)%4)*8;w.push((bit/M)|0,bit);for(let j=0;j<w.length;){const x=w.slice(j,j+=16),old=hash.slice();for(let i=0;i<64;i++){const w15=x[i-15],w2=x[i-2],a=hash[0],e=hash[4];const t1=(hash[7]+(rotr(e,6)^rotr(e,11)^rotr(e,25))+((e&hash[5])^((~e)&hash[6]))+k[i]+(x[i]=i<16?x[i]:((x[i-16]+(rotr(w15,7)^rotr(w15,18)^(w15>>>3))+x[i-7]+(rotr(w2,17)^rotr(w2,19)^(w2>>>10)))|0)))|0;const t2=((rotr(a,2)^rotr(a,13)^rotr(a,22))+((a&hash[1])^(a&hash[2])^(hash[1]&hash[2])))|0;hash.unshift((t1+t2)|0);hash[4]=(hash[4]+t1)|0;hash.pop();}for(let i=0;i<8;i++)hash[i]=(hash[i]+old[i])|0;}let out='';for(let i=0;i<8;i++)for(let j=3;j>=0;j--){const b=(hash[i]>>(j*8))&255;out+=(b<16?'0':'')+b.toString(16);}return out;}
export function stableImportKey(products:CanonicalProductInput[]){return sha256Ascii(stable(products));}
