import { Hono } from 'hono'; import { cors } from 'hono/cors'; import { secureHeaders } from 'hono/secure-headers'; import { canonicalProductSchema,parseCsvCatalog } from '../shared/catalog-contract'; import { categoryInputSchema,importRequestSchema,storeSettingsInputSchema,validE164 } from '../shared/schemas'; import { adminChallenge,authenticateAdmin,validMutationOrigin } from './auth'; import { KvStoreRepository,StoreWriteRateLimitedError } from './repositories/store-repository'; import { CatalogService } from './services/catalog-service'; import { ImportService } from './services/import-service'; import { MediaService,type UploadInput } from './services/media-service'; import { MEDIA_SENTINEL_KEY } from './store-state'; import type { Env,Variables } from './types';
const err=(code:string,message?:string)=>({error:{code,...(message?{message}:{})}}),jsonFile=(value:FormDataEntryValue|null)=>value instanceof File?value:null,repository=(env:Env)=>new KvStoreRepository(env.STORE_KV,{bootstrapIfMissing:env.ENVIRONMENT==='test'}),catalog=(env:Env)=>new CatalogService(repository(env));
function rethrowRate(error:unknown){if(error instanceof StoreWriteRateLimitedError||(error instanceof Error&&error.message==='write_rate_limited'))throw error;}
export function createApp(){const app=new Hono<{Bindings:Env;Variables:Variables}>(); app.use('*',async(c,next)=>{const allowed=(c.env?.PUBLIC_ORIGINS??'').split(',').map(v=>v.trim()).filter(Boolean);return cors({origin:o=>allowed.includes(o)?o:'',allowMethods:['GET','HEAD','OPTIONS','POST','PUT','PATCH','DELETE'],allowHeaders:['content-type','x-test-admin'],exposeHeaders:['etag'],credentials:false})(c,next);}); app.use('*',secureHeaders({xContentTypeOptions:'nosniff',referrerPolicy:'strict-origin-when-cross-origin',xFrameOptions:'DENY',strictTransportSecurity:'max-age=31536000; includeSubDomains',contentSecurityPolicy:{defaultSrc:["'self'"],imgSrc:["'self'",'data:','blob:'],styleSrc:["'self'","'unsafe-inline'"],fontSrc:["'self'"],scriptSrc:["'self'"],connectSrc:["'self'",'https://rebeca-sf.simondalmasso44.workers.dev'],frameAncestors:["'none'"]}})); app.onError((error,c)=>{console.error(error);if(error instanceof StoreWriteRateLimitedError||(error instanceof Error&&error.message==='write_rate_limited'))return c.json(err('write_rate_limited','Guardado temporalmente limitado. Reintentá en un segundo.'),429);if(error instanceof Error&&/^store_state_/.test(error.message))return c.json(err(error.message,'El almacenamiento del catálogo no está disponible.'),503);return c.json(err('internal_error','No se pudo completar la operación.'),500);});
app.get('/api/health',async c=>{let store='ok',media='ok';try{await repository(c.env).read();}catch{store='error';}try{const sentinel=await c.env.MEDIA_KV.get(MEDIA_SENTINEL_KEY);if(sentinel===null&&c.env.ENVIRONMENT!=='test')media='error';}catch{media='error';}const ok=store==='ok'&&media==='ok';return c.json({ok,sha:c.env.BUILD_SHA,environment:c.env.ENVIRONMENT,storage:'kv',store,media},ok?200:503);});
app.get('/media/*',async c=>{let key='';try{key=decodeURIComponent(c.req.path.slice('/media/'.length));}catch{return c.json(err('not_found'),404);}if(!/^media\/[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+\/(original|720|1440)\.(jpg|png|webp|avif)$/.test(key))return c.json(err('not_found'),404);const item=await c.env.MEDIA_KV.getWithMetadata<{contentType?:string;sha256?:string}>(key,'arrayBuffer');if(!item.value)return c.json(err('not_found'),404);const headers=new Headers({'content-type':item.metadata?.contentType??'application/octet-stream','cache-control':'public, max-age=31536000, immutable','x-content-type-options':'nosniff'});if(item.metadata?.sha256)headers.set('etag','"'+item.metadata.sha256+'"');return new Response(item.value,{headers});});
app.get('/api/catalog',async c=>c.json(await catalog(c.env).listPublic())); app.get('/api/catalog/products/:slug',async c=>{const p=await catalog(c.env).getPublicBySlug(c.req.param('slug'));return p?c.json(p):c.json(err('not_found','Producto no encontrado.'),404);}); app.get('/api/store-settings/public',async c=>{const s=await catalog(c.env).getSettings();return c.json({storeName:s.storeName,instagramUrl:s.instagramUrl,whatsappNumber:s.whatsappNumber,deliveryLabel:s.deliveryLabel,pickupLabel:s.pickupLabel,demoMode:s.demoMode,catalogRevision:s.catalogRevision});});
app.use('*',async(c,next)=>{
  const adminPath=c.req.path==='/admin'||c.req.path.startsWith('/admin/')||c.req.path==='/api/admin'||c.req.path.startsWith('/api/admin/');
  if(!adminPath)return next();
  const actor=await authenticateAdmin(c.req.raw,c.env);
  if(!actor)return adminChallenge();
  if(c.req.path.startsWith('/api/admin')&&!validMutationOrigin(c.req.raw,c.env))return c.json(err('invalid_origin','Origen no autorizado.'),403);
  c.set('actor',actor);
  await next();
});
app.get('/api/admin/products',async c=>c.json(await catalog(c.env).listAdmin())); app.get('/api/admin/products/:id',async c=>{const p=await catalog(c.env).getAdminProduct(c.req.param('id'));return p?c.json(p):c.json(err('not_found'),404);}); app.post('/api/admin/products',async c=>{const p=canonicalProductSchema.safeParse(await c.req.json().catch(()=>null));if(!p.success)return c.json({error:{code:'validation_error',issues:p.error.issues}},400);return c.json(await catalog(c.env).upsertProduct(p.data,c.get('actor')),201);}); app.put('/api/admin/products/:id',async c=>{const p=canonicalProductSchema.safeParse(await c.req.json().catch(()=>null));if(!p.success)return c.json({error:{code:'validation_error',issues:p.error.issues}},400);try{return c.json(await catalog(c.env).updateProduct(c.req.param('id'),p.data,c.get('actor')));}catch(error){rethrowRate(error);return c.json(err('not_found'),404);}});
app.post('/api/admin/products/:id/status',async c=>{const b=await c.req.json().catch(()=>null) as {status?:string}|null;if(!b||!['draft','published','archived'].includes(b.status??''))return c.json(err('validation_error'),400);try{return c.json(await catalog(c.env).setStatus(c.req.param('id'),b.status as 'draft'|'published'|'archived',c.get('actor')));}catch(error){rethrowRate(error);return c.json(err('not_found'),404);}}); app.post('/api/admin/products/:id/duplicate',async c=>{try{return c.json(await catalog(c.env).duplicateProduct(c.req.param('id'),c.get('actor')),201);}catch(error){rethrowRate(error);return c.json(err('not_found'),404);}});
app.get('/api/admin/categories',async c=>c.json(await catalog(c.env).listCategories())); app.post('/api/admin/categories',async c=>{const p=categoryInputSchema.safeParse(await c.req.json().catch(()=>null));if(!p.success)return c.json({error:{code:'validation_error',issues:p.error.issues}},400);try{return c.json(await catalog(c.env).createCategory(p.data,c.get('actor')),201);}catch(error){rethrowRate(error);return c.json(err('duplicate_slug'),409);}}); app.put('/api/admin/categories/:id',async c=>{const p=categoryInputSchema.safeParse(await c.req.json().catch(()=>null));if(!p.success)return c.json({error:{code:'validation_error',issues:p.error.issues}},400);try{return c.json(await catalog(c.env).updateCategory(c.req.param('id'),p.data,c.get('actor')));}catch(error){rethrowRate(error);return c.json(err(error instanceof Error&&error.message==='duplicate_slug'?'duplicate_slug':'not_found'),error instanceof Error&&error.message==='duplicate_slug'?409:404);}});
app.get('/api/admin/settings',async c=>c.json(await catalog(c.env).getSettings())); app.put('/api/admin/settings',async c=>{const p=storeSettingsInputSchema.safeParse(await c.req.json().catch(()=>null));if(!p.success||!validE164(p.success?p.data.whatsappNumber:null))return c.json({error:{code:'validation_error',issues:p.success?[]:p.error.issues}},400);return c.json(await catalog(c.env).updateSettings(p.data,c.get('actor')));});
async function importRows(format:'csv'|'json',payload:string|unknown[]){return format==='csv'?parseCsvCatalog(String(payload)):(Array.isArray(payload)?payload:JSON.parse(String(payload)));} app.post('/api/admin/import/preview',async c=>{const p=importRequestSchema.safeParse(await c.req.json().catch(()=>null));if(!p.success)return c.json({error:{code:'validation_error',issues:p.error.issues}},400);try{const repo=repository(c.env),svc=new CatalogService(repo);return c.json(await new ImportService(repo,svc).preview(await importRows(p.data.format,p.data.payload),p.data.sourceName,p.data.format));}catch(error){rethrowRate(error);return c.json(err('import_parse_error',error instanceof Error?error.message:'Importación inválida.'),400);}}); app.post('/api/admin/import/apply',async c=>{const p=importRequestSchema.safeParse(await c.req.json().catch(()=>null));if(!p.success)return c.json({error:{code:'validation_error',issues:p.error.issues}},400);try{const repo=repository(c.env),svc=new CatalogService(repo);return c.json(await new ImportService(repo,svc).apply(await importRows(p.data.format,p.data.payload),p.data.sourceName,p.data.format,c.get('actor')));}catch(error){rethrowRate(error);return c.json(err('import_parse_error',error instanceof Error?error.message:'Importación inválida.'),400);}});
app.get('/api/admin/export/json',async c=>{const data=await catalog(c.env).exportCanonical();c.header('content-disposition','attachment; filename="rebeca-catalog.json"');return c.json(data);}); app.get('/api/admin/export/csv',async c=>{const data=await catalog(c.env).exportCanonical(),headers=['externalId','slug','title','subtitle','description','categorySlug','priceCents','compareAtPriceCents','status','featured','source','sourceName','demoData','variants'],esc=(v:unknown)=>'"'+(typeof v==='string'?v:JSON.stringify(v??'')).replace(/"/g,'""')+'"',csv=[headers.join(','),...data.map(p=>headers.map(h=>esc((p as unknown as Record<string,unknown>)[h])).join(','))].join('\r\n');c.header('content-disposition','attachment; filename="rebeca-catalog.csv"');c.header('content-type','text/csv; charset=utf-8');return c.body(csv);});
app.post('/api/admin/products/:id/media',async c=>{const form=await c.req.formData(),original=jsonFile(form.get('original')),small=jsonFile(form.get('small')),large=jsonFile(form.get('large'));if(!original)return c.json(err('validation_error','Falta imagen original.'),400);let meta:{altText?:string;width?:number;height?:number;sourceUrl?:string;sourceKind?:UploadInput['sourceKind']}={};try{meta=JSON.parse(String(form.get('meta')??'{}'));}catch{return c.json(err('validation_error','Metadata inválida.'),400);}try{const input:UploadInput={original:{data:await original.arrayBuffer(),type:original.type},altText:String(meta.altText??''),width:Number(meta.width??0),height:Number(meta.height??0),sourceUrl:meta.sourceUrl,sourceKind:meta.sourceKind};if(small)input.small={data:await small.arrayBuffer(),type:small.type};if(large)input.large={data:await large.arrayBuffer(),type:large.type};return c.json(await new MediaService(repository(c.env),c.env.MEDIA_KV).upload(c.req.param('id'),input,c.get('actor')),201);}catch(error){rethrowRate(error);return c.json(err(error instanceof Error?error.message:'media_upload_failed'),400);}});
app.delete('/api/admin/media/:id',async c=>{try{return c.json(await new MediaService(repository(c.env),c.env.MEDIA_KV).remove(c.req.param('id'),c.get('actor')));}catch(error){rethrowRate(error);return c.json(err('not_found'),404);}}); app.put('/api/admin/products/:id/media/order',async c=>{const b=await c.req.json().catch(()=>null) as {ids?:string[]}|null;if(!b||!Array.isArray(b.ids))return c.json(err('validation_error'),400);try{return c.json(await new MediaService(repository(c.env),c.env.MEDIA_KV).reorder(c.req.param('id'),b.ids,c.get('actor')));}catch(error){rethrowRate(error);return c.json(err(error instanceof Error?error.message:'media_reorder_failed'),400);}});
app.notFound(async c=>c.req.path.startsWith('/api/')?c.json(err('not_found','Ruta no encontrada.'),404):c.env.ASSETS.fetch(c.req.raw)); return app;}
