import { z } from 'zod';
import { availabilitySchema,catalogSourceSchema,productStatusSchema } from '../shared/catalog-contract';
import { categoryInputSchema,storeSettingsInputSchema } from '../shared/schemas';
export const STORE_STATE_KEY='store:state:v1'; export const MEDIA_SENTINEL_KEY='media:sentinel';
export const storedVariantSchema=z.object({id:z.string().min(1),externalId:z.string().min(1).optional(),sku:z.string().min(1).optional(),size:z.string().min(1).optional(),color:z.string().min(1).optional(),priceOverrideCents:z.number().int().nonnegative().optional(),availability:availabilitySchema,stockQty:z.number().int().nonnegative().nullable().optional(),active:z.boolean()});
export const storedMediaSchema=z.object({id:z.string().min(1),altText:z.string().min(1),originalKey:z.string().min(1),smallKey:z.string().nullable(),largeKey:z.string().nullable(),sourceUrl:z.string().url().nullable(),sourceKind:z.enum(['upload','instagram_public','demo_generated']),sha256:z.string().regex(/^[a-f0-9]{64}$/),width:z.number().int().positive().nullable(),height:z.number().int().positive().nullable(),contentType:z.enum(['image/jpeg','image/png','image/webp','image/avif']),sortOrder:z.number().int().nonnegative(),createdAt:z.string(),updatedAt:z.string()});
export const storedProductSchema=z.object({id:z.string().min(1),externalId:z.string().min(1).optional(),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),title:z.string().min(1),subtitle:z.string().optional(),description:z.string(),categorySlug:z.string().optional(),priceCents:z.number().int().nonnegative(),compareAtPriceCents:z.number().int().nonnegative().optional(),currency:z.literal('ARS'),status:productStatusSchema,featured:z.boolean(),variants:z.array(storedVariantSchema).min(1),media:z.array(storedMediaSchema),source:catalogSourceSchema,sourceName:z.string().optional(),demoData:z.boolean(),createdAt:z.string(),updatedAt:z.string()});
export const storedCategorySchema=categoryInputSchema.extend({id:z.string().min(1),updatedAt:z.string()}); export const storedSettingsSchema=storeSettingsInputSchema.extend({catalogRevision:z.number().int().nonnegative(),updatedAt:z.string()});
export const importRunSchema=z.object({id:z.string().min(1),sourceKind:z.enum(['csv','json','erp']),sourceName:z.string().min(1),status:z.literal('applied'),checksum:z.string().min(1),createdCount:z.number().int().nonnegative(),updatedCount:z.number().int().nonnegative(),skippedCount:z.number().int().nonnegative(),errorCount:z.number().int().nonnegative(),errors:z.array(z.object({index:z.number().int(),message:z.string()})),createdAt:z.string(),appliedAt:z.string()});
export const auditEventSchema=z.object({id:z.string().min(1),actor:z.string().min(1),action:z.string().min(1),entityType:z.string().min(1),entityId:z.string().min(1),before:z.unknown().nullable(),after:z.unknown().nullable(),createdAt:z.string()});
export const storeStateSchema=z.object({schemaVersion:z.literal(1),revision:z.number().int().nonnegative(),products:z.array(storedProductSchema),categories:z.array(storedCategorySchema),settings:storedSettingsSchema,importRuns:z.array(importRunSchema),auditEvents:z.array(auditEventSchema),updatedAt:z.string()});
export type StoreStateV1=z.infer<typeof storeStateSchema>; export type StoredProduct=z.infer<typeof storedProductSchema>; export type StoredCategory=z.infer<typeof storedCategorySchema>; export type StoredMedia=z.infer<typeof storedMediaSchema>;
export function emptyStoreState(now=new Date().toISOString()):StoreStateV1{return{schemaVersion:1,revision:0,products:[],categories:[],settings:{storeName:'REBECA',instagramUrl:'https://www.instagram.com/rebeca_santafee/',whatsappNumber:null,deliveryLabel:'Coordinar envío',pickupLabel:'Retiro',demoMode:true,catalogRevision:0,updatedAt:now},importRuns:[],auditEvents:[],updatedAt:now};}
